h:
	@gcc -o H H.c -L/usr/local/ssl/lib/ -I/usr/local/ssl/include -lcrypto
pad:
	@gcc -o Pad Pad.c -L/usr/local/ssl/lib/ -I/usr/local/ssl/include -lcrypto
decrypt:
	@gcc -o decrypt decrypt.c -L/usr/local/ssl/lib/ -I/usr/local/ssl/include -lcrypto

